package reports;

/**
 * Represents the different report types available in the Personal Finance
 * Manager (PFM) application.
 *
 * <p>
 * Each constant identifies a report that can be generated by the
 * ReportManager and selected through the ReportMenu.
 * </p>
 *
 * @author Alyssa Johnson
 * @version 1.0
 * @since 1.0
 */
public enum ReportType {

    /**
     * Generates a complete financial report for a selected year.
     */
    ANNUAL,

    /**
     * Generates a financial summary for a selected month.
     */
    MONTHLY,

    /**
     * Generates yearly totals for each income and expense category.
     */
    CATEGORY_TOTALS,

    /**
     * Generates an overall budget performance summary.
     */
    BUDGET_SUMMARY

}